create or replace PACKAGE test_pkg_employee IS

   /* generated by utPLSQL for SQL Developer on 2021-03-27 00:30:25 */

   --%suite(test_pkg_employee)
   --%suitepath(alltests)

   --%test
   PROCEDURE p_get_employee;
   
   --%test
   PROCEDURE p_employee_no_data_found;

   --%test
   PROCEDURE p_create_employee;
   
   --%test
   PROCEDURE p_create_emp_fk_constraing;
   
   --%test
   PROCEDURE p_emp_not_null_const;

   --%test
   PROCEDURE p_increase_salary;
   
   --%test
   PROCEDURE p_inc_sal_no_user;
   
   --%test
   PROCEDURE p_inc_sal_w_sal_percent;
   
   --%test
   PROCEDURE p_inc_sal_w_sal_percent2;

   --%test
   PROCEDURE p_decrease_salary;
   
   --%test
   PROCEDURE p_dec_sal_no_user;
   
    --%test
   PROCEDURE p_dec_sal_wrg_perc;
   
    --%test
   PROCEDURE p_dec_sal_wrg_perc2;

   --%test
   PROCEDURE p_transfer_employee;
   
   --%test
   PROCEDURE p_transf_emp_empty;
   
   --%test
   PROCEDURE p_transf_emp_wrg_dep;

   --%test
   PROCEDURE p_get_salary;
   
   --%test
   PROCEDURE p_get_sal_no_usr;

END test_pkg_employee;